version: "3"
services:
  web:
    image: register-patient
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb+srv://Admin:Aa112233@backendtest.xionozq.mongodb.net/test
